import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-1WK8W0653J"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments)}
        gtag('js', new Date());

        gtag('config', 'G-1WK8W0653J');
      </script>
      <title>default</title>
      <meta
          name="description"
          content="default"
          key="desc"
      />
    </head>
    <body className={inter.className}>

    {children}
    <!-- Google tag (gtag.js) -->

    </body>
    </html>
  );
}
