import { Inter } from "next/font/google";
import "./globals.css";
import GoogleAnalitic from "@/app/googleAnalitic";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <GoogleAnalitic ga_id={'G-1WK8W0653J'} />
    {children}
    </body>
    </html>
  );
}
