import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>

      <title>default</title>
      <meta
          name="description"
          content="default"
          key="desc"
      />
    </head>
    <body className={inter.className}>
    {children}
    </body>
    </html>
  );
}
